### ISSUE TITLE
can i use bert as embedding?

### ISSUE THREAD

**Issue by lqsunshine** [TTdeveloping/CNN_BiLSTM_CRF_NER#1]
if i use the bert, will the effect be better?

**Comment by TTdeveloping** [comment]
I do not use Bert at present, but some papers use Bert on NER tasks and achieve good results. I think you can try it. I'll try it after I learn Bert.

**Comment by TTdeveloping** [comment]
@lqsunshine  I do not use bert at present, but some papers use bert on NER tasks and achieve good results. I think you can try it. I'll try it after I learn bert.
